### ISSUE TITLE
failed for URL: "flic://" 

### ISSUE THREAD

**Issue by hakim-ali** [50ButtonsEach/ios-boilerplate-swift#1]
First project give me this exception after adding the sdk.
Call can throw, but it is not marked with 'try' and the error is not handled

on this line.

self.button = self.manager?.generateButtonFromURL(url)

When i add the try catch then project run fine but i am getting this exception.

canOpenURL: failed for URL: "flic://" - error: "This app is not allowed to query for scheme flic"

**Comment by AntonMeier** [comment]
Please take a look at step 5 under "Set Up Xcode" in our tutorial: https://flic.io/partners/developers/ios-tutorial

We have not yet updated the boilerplate-app for the newest version of the lib.

**Comment by hakim-ali** [comment]
I update the handle URL scheme calls as per step 5 but its not working. Can you update the example the boilerplate-app for the newest version of the lib.

**Comment by hakim-ali** [comment]
<img width="612" alt="screen shot 2016-01-04 at 9 51 53 am" src="https://cloud.githubusercontent.com/assets/9202901/12084148/d7d54ff0-b2c8-11e5-9f67-cf4b8d87f2af.png">

Can you please look into this , and let me know if i am missing something,

I also change this line in code.
self.manager?.requestButtonFromFlicAppWithCallback("Apphops.flic://button")

**Comment by AntonMeier** [comment]
LSApplicationQueriesSchemes should be an array containing a string and not a string on its own. Please look again at that section in the tutorial.

**Comment by hakim-ali** [comment]
Thank you soo much, its working now.

One more thing, the sample code only showing the code for single click, how i can implement the double click and hold.

**Comment by AntonMeier** [comment]
Good, no problems!
Have a look at all available delegate callbacks here: https://flic.io/partners/developers/documentation/ios/Protocols/SCLFlicButtonDelegate.html

**Comment by hakim-ali** [comment]
Thank you for your quick help.

**Comment by SharadExt** [comment]
I have an error for developing flic iOS app.
value of SCLFlicManager has no member requestButtonFromFLicAppWithCallBack.
  Can anybody send me sample app for flic .How to configure flic functionality within our apps? please help .

**Comment by SharadExt** [comment]
I read and followed tutorial https://flic.io/partners/developers/ios-tutorial but it giving me error that SCLFLicManager has not that methods . So I think is SDK  wrong? Because methods which are used in that tutorial are not there in header files. So What I have to do?
Check my app also.
[Flick Example_2.zip](https://github.com/50ButtonsEach/ios-boilerplate-swift/files/244556/Flick.Example_2.zip)

**Comment by hakim-ali** [comment]
follow this sample code.
https://github.com/50ButtonsEach/ios-boilerplate-swift

I implement Flic with my application with above sample code.

**Comment by SharadExt** [comment]
Hi Hakim ,
Thanks for this. Can you please tell me how to configure flic functionality in our apps?

**Comment by SharadExt** [comment]
I just want to do one thing that when I pressed flic that time it should generated one alert view in my app. Is this possible ?

**Comment by SharadExt** [comment]
Why double click is not working?

**Comment by hakim-ali** [comment]
Yes this is very basic example of flic.

I will check your sample later today or tomorrow morning.

**Comment by SharadExt** [comment]
My alert view is generated for single and hold button. But double click is not working.

**Comment by AntonMeier** [comment]
Hello. I would like to point out, like you have noticed, that the tutorial on /partners/developers/ios-tutorial has not yet been updated to the latest version of the SDK. This will be done soon. 

Regarding the double click, you have to set the value of the triggerBehavior property to SCLFlicButtonTriggerBehaviorClickAndDoubleClickAndHold. By default you only get click and hold. The reason for this is that if we want to detect double click then we need to add a slight delay to click events in order to distinguish click from double click.

**Comment by SharadExt** [comment]
Thanks, It works
